repos:
- repo: git@github.com:dnephin/pre-commit-golang.git
  rev: v0.3.5
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-imports
    - id: validate-toml
- repo: local
  hooks:
    - id: go-mod-tidy
      name: 'go mod tidy'
      entry: custom-hooks/go-mod-tidy.sh
      files: '(\.go)|(\.mod)|(\.sum)$'
      language: 'script'
      description: "Runs `gofmt`, requires golang"
- repo: git@github.com:kadrach/pre-commit-gitlabci-lint.git
  rev: ab984c60414b012e294a65166691473047ccce49
  hooks:
  - id: gitlabci-lint
